services:
  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123+
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3360:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-proot123+']
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-root}
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_port_connectivity']
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
  ms-postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ms_email_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:-ms_email}
    volumes:
      - ms_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
  ms-pgadmin:
    image: dpage/pgadmin4:8.14
    restart: unless-stopped
    profiles: ["dev"]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@local.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?err}
      PGADMIN_CONFIG_SERVER_MODE: 'False' # Not for production
    volumes:
      - ms-pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      ms-postgres:
        condition: service_healthy
volumes:
  mysql_data:
  rabbitmq_data:
  ms_postgres_data:
  ms_pgadmin_data:
